### ISSUE TITLE
number of training images

### ISSUE THREAD

**Issue by elifbykl** [jaspereb/FasterRCNNTutorial#1]
Firstly, a very useful video. I applied my work as described on the video. What I need to change for smaller objects. How many images have you trained on your dataset, how many positive objects should be selected (1000, 2000, etc)?

**Comment by elifbykl** [comment]
Thank you for your answer. I will try.

**Comment by elifbykl** [comment]
Hi Jaspereb,
The detection results are really good but there is a problem. In some areas, large detection windows are formed, and there are more than one object in it. I used the following values. Are these values reasonable?

scales: [0.05, 0.10, 0.25, 0.5, 1.0, 2.0]
aspect_ratios: [0.05, 0.10, 0.15, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0]

**Comment by jaspereb** [comment]
The way fasterRCNN is set up it will try and find the smallest bounding box that definitely contains the object which leaves it prone to the issue you are having. lowering the scales is the easiest way around this but will only work if your objects are all smaller than a certain fixed size, below that size you may still get grouping and would need more advanced techniques to fix this.

For the resnet101 model at least:
The base anchor size is 255,255.

The anchor ratios will multiply the x dimension and divide the y dimension, so if you have an aspect ratio of 0.5 your 255x255 anchor becomes 128x510. Each aspect ratio in the list is applied, then the results are multiplied by the scales. So the first step is to resize your images to the training/testing size, then manually check what the smallest and largest objects you expect are, and what the most extreme aspect ratios will be. Set up the config file with values that will cover these cases when the base anchor size is adjusted by the aspect ratios and multiplied by the scales.

If your largest object is 50*50 pix after resizing then use a scale of 0.2.
